config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'top/about', to: 'top#about'
  get 'top/search', to: 'top#search'

  get 'relationships/create'
  get 'relationships/destroy'
  resources :relationships, only: [:create, :destroy]

  get 'inquiries', to: 'inquiries#index'
  post 'inquiries/confirm', to: 'inquiries#confirm'
  post 'inquiries/complete', to: 'inquiries#complete'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
  get 'emails', to: 'emails#index'
  post 'emails/confirm', to: 'emails#confirm'
  post 'emails/complete', to: 'emails#complete'
    member do
      get :followings
      get :followers
    end
    collection do
      get :search
      get :about
    end
  end

  resources :products do
     collection do
      get :search
      get :about
    end
  end

  resources :comments, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :search
    end
  end

resources :notices do
      collection do
      get :search
      get :about
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # default_scope { order(created_at: :desc)}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: []
         # :confirmable

has_many :user_works
has_many :works, through: :user_works
accepts_nested_attributes_for :user_works, allow_destroy: true
# accepts_nested_attributes_for :tag_works, allow_destroy: true
has_many :products, ->{ order("created_at DESC")}, dependent: :delete_all
has_many :comments, ->{ order("updated_at DESC") }, dependent: :delete_all
has_many :commented_products, ->{ order("updated_at DESC") }, through: :comments, source: :product, dependent: :delete_all


validates :text, length: { maximum: 100 }

has_many :relationships
has_many :followings, through: :relationships, source: :follow
# user.followingsでuserがフォローしているuser達を取得
has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
has_many :followers, through: :reverses_of_relationship, source: :user
has_many :emails
has_one :notice, dependent: :destroy

  def email_required?
    false
  end

  def email_changed?
    false
  end

mount_uploader :avatar, AvatarsUploader

  enum location: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,海外:48
  }

  validate :add_error

  def self.search_work(works)
      workgenre = UserWork.searchworks(works)
      self.where(id: workgenre)
  end

  def self.count_order(count)
    if count == "1"
      self.reorder("products_count DESC")
    elsif count == "2"
    self.joins(:followers).includes(:followers).group(:user_id).reorder("count(user_id) DESC")
    elsif count == "3"
    self.reorder("created_at DESC")
    elsif count == "4"
    self.reorder("created_at ASC")
    end
  end


  def add_error
    errors[:base] << "苗字は必須です。" if familyname.blank?
    # errors[:base] << "登録メールアドレスは必須です。" if email.blank?
  end

def name
   self.familyname
end

def follow(other_user)
  unless self == other_user
    self.relationships.find_or_create_by(follow_id: other_user.id)
  end
end

def unfollow(other_user)
  relationship = self.relationships.find_by(follow_id: other_user.id)
  relationship.destroy if relationship
end

def following?(other_user)
  self.followings.include?(other_user)
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:edit, :update, ]

  def index
    @users = User.where(offer: "1").order("id DESC").page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @tags = @user.user_works
    @products = Product.where(user_id: @user.id).select(:id, :title, :location, :category, :completion).limit(10)
    @photos = WholePhoto.group(:product_id)
    @notice = @user.notice
    @commented = @user.commented_products.distinct.limit(10)
  end

  def search
    @users = User.select(:id, :familyname, :location, :avatar, :text,).order("id DESC")
    @users = @users.where(offer: "1")
    @users = @users.count_order(params[:count]) if params[:count].present?
    @users = @users.search_work(params[:work_user]) if params[:work_user] && params[:work_user].compact.reject(&:empty?).present?
    @users = @users.search_work(params[:work_id]) if params[:work_id].present?
    @users = @users.where(location: params[:location]) if params[:location].present?
    @users = @users.page(params[:page]).per(20)
  end

  def about
  end

  def edit
    @user = User.find(current_user.id)
    # @user.avatar.cache! unless @user.avatar.blank?
  end

  def update
    user = User.find(current_user.id)
    if user.update(update_params)
      redirect_to user_path(current_user)
    else
      @user = User.find(current_user.id)
      render action: :edit
    end
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings

  end

  def followers
    user = User.find(params[:id])
    @users = user.followers

  end

private

def update_params
  params.require(:user).permit(:familyname, :email, :location, :office, :phone, :address, :local, :url, :avatar, :offer, :text, :avatar_cache,:remove_avatar, { :work_ids=> [] })
end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notice.html.erb
<article>
<%= link_to(notice_path(@user.notice.id), class: 'list-content') do %>
<h5><%= notice.title %></h5>
<h6><%= notice.created_at.strftime('更新 ： %Y/%m/%d') %></h6>
<h6><%= notice.text.truncate(150) %></h6>
<% end %>
</article>

app/views/users/_product.html.erb
<div class="swiper-slide">
    <article>
     <% @photos.each do | top | %>
        <% if product.id == top.product_id %>
        <%= link_to image_tag(top.photo_url), product_path(product.id), :class => "img" %>
        <% end %>
     <% end %>
    <div class="text">
　　　　　<h6><%= product.title %></h6>
        <a><%= fa_icon("map-marker") %><%= product.location %></a></br>
        <%= link_to product.category, search_products_path(category: product.category) %></br>
        <a><%= product.completion.strftime("%Y-%m") %>  <%= fa_icon("comments") %><%= product.comments.count %><%= fa_icon("eye") %><%= product.impressions.count %></a>
     </div>
     </article>
</div>

app/views/users/_user.html.erb
<article>
  <div class="contentA">

    <div class="imgA">
    <%= image_tag user.avatar_url, :class => "img" %>
    </div>

    <div class="conA">

      <div class="con1">
    <%= link_to user.name.truncate(10), user_path(user.id) %>

      </div>
      <div class="con3">
        <% if user.location? %>
      <p><%= fa_icon("map-marker") %>  <%= user.location %></p>
      <% end %>
      </div>
      <div class="con2">
      <% if user.works && user.works.count >= 4 %>
      <div class="tagA">
        <% user.works.each_with_index do |work, i|%>
        <p><%= link_to work.tag, search_users_path(work_id: work.id) %></p>
        <% break if i== 3 %>
        <% end %>...</div>
      <% elsif user.works %>
      <div class="tagA">
        <% user.works.each do |work|%>
        <p><%= link_to work.tag, search_users_path(work_id: work.id) %></p>
        <% end %></div>
      <% else %>
      <% end %>
      </div>

    </div>

  </div>


</article>

app/views/users/about.html.erb
<%= stylesheet_link_tag    'devise/user', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="usernew">

<h2>ユーザー検索</h2>

<%= form_with url: search_users_path, method: :get, local: true do |f| %>

     <div class="field">
     <p><%= f.label :主な勤務地 %></p>
     <%= f.select :location, User.locations.keys,{prompt: '選択してください'},  class: 'localform' %><br />
     </div>

     <div class="field check">
     <p><%= f.label :仕事内容 %></p>
     <label><div class= "tag"><%= f.collection_check_boxes(:work_user, Work.all, :id, :tag) do |b| %>
      <%=  b.check_box %><a><%= b.label { b.text } %></a>
     <% end %></div>
     </label>
     </div>

  <div class="field">
  <p><%= f.label :表示の順番 %></p>
  <%= f.select :count, [["投稿が多い順", "1"], ["フォロワーが多い順", "2"], ["登録が新しい順", "3"], ["登録が古い順", "4"]], {prompt: '選択してください'}, class: 'user form' %><br />
  </div>

     <div class="field">
     <%= f.submit "検索", class: ' user button', name: nil %>
     </div>
     <% end %>

</div>

app/views/users/edit.html.erb
<%= stylesheet_link_tag    'devise/user', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="usernew">

<h2>プロフィール編集</h2>
<p>（ ※は必須 ）</p>

   <%= form_with model: @user, local: true do |f| %>

     <div class="field">
        <p><%= f.label :氏名または会社名 %><a>※</a></p>
     <%= f.text_field :familyname, autofocus: true, autocomplete: "familyname", :maxlength => "18",  class: 'user form' %>
     </div>

     <div class="field">
     <p><%= f.label :登録メールアドレス %><a>※</a></p>
     <%= f.email_field :email, autofocus: true, autocomplete: "email",   class: 'user form' %>
     </div>

     <div class="field">
     <p><%= f.label :所属 %><br ><a>(学生の方は学校名)</a></p>
     <%= f.text_field :office, autofocus: true, autocomplete: "office",  class: 'user form' %>
     </div>

     <div class="field">
     <p><%= f.label :勤務地または居住地 %></p>
     <%= f.select :location, User.locations.keys,  class: 'user form' %><br />
     <%= f.text_field :local, autofocus: true, autocomplete: "local", placeholder: "都道府県以降の住所", class: 'user form' %>
     </div>

     <div class="field check">
     <p><%= f.label :"仕事または興味のある分野" %></p>
     <label><div class= "tag"><%= f.collection_check_boxes(:work_ids, Work.all, :id, :tag) do |b| %>
      <%=  b.check_box %><a><%= b.label { b.text } %></a>
     <% end %></div>
     </label>
     </div>

     <div class="field">
      <p><%= f.label :メールアドレス %><br ><a>メッセージ受信用<br >(メールアドレスは表示されません)</a></p>
      <%= f.email_field :address, autofocus: true, autocomplete: "address",  placeholder: "", class: 'user form' %>
     </div>

     <div class="field">
     <p><%= f.label :電話番号 %></p>
     <%= f.telephone_field :phone, autofocus: true, autocomplete: "phone",  placeholder: "マイページに掲載可能な電話番号", class: 'user form' %>
     </div>

     <div class="field">
     <p><%= f.label :ホームページ %></p>
     <%= f.url_field :url, autofocus: true, autocomplete: "url",  placeholder: "マイページに掲載可能なurl", class: 'user form' %>
     </div>

     <div class="field avater_photo">
     <p><%= f.label :プロフィール画像 %></p>
     <label>
     <% if @user.avatar? %>
     <%= image_tag @user.avatar_url, id: :avatar_prev, :class => "img" %>
     <% else %>
     <%= image_tag 'default.png', id: :avatar_prev, :class => "img default" %>
     <% end %>
     <%= f.file_field :avatar, autofocus: true , id: :user_avatar %>
     <%= f.hidden_field :avatar_cache %>
     </label><br >
     <% if @user.avatar? %>
     <label><p class="user_remove"><%= f.check_box :remove_avatar %><%= fa_icon("times") %>削除</p></label>
     <% else %>
     <label><p class="user_remove" style="display:none;"><%= f.check_box :remove_avatar %><%= fa_icon("times") %>削除</p></label>
     <% end %>
     </div>

     <div class="field">
     <p><%= f.label :紹介コメント %></p>
     <p><label>残り：<span class="count">0</span>文字</label></p>
     <%= f.text_area :text, autofocus: true, :maxlength => "100", autocomplete: "text",  placeholder: "", class: 'user form text' %>
     </div>

     <div class="field">
     <label><%= f.check_box :offer, { class: 'userform' }, 'true', 'false' %>一覧・検索で表示させる</label>
     <br />
     </div>


     <div class="field">
     <%= f.submit "プロフィールを保存", class: 'user button' %>
     </div>
     <% end %>

</div>

<script>

$(function(){
    var countMax = 100;
    $('textarea').bind('keydown keyup keypress change',function(){
        var thisValueLength = $(this).val().length;
        var countDown = (countMax)-(thisValueLength);
        $('.count').html(countDown);

        if(countDown < 0){
            $('.count').css({color:'#ff0000',fontWeight:'bold'});
        } else {
            $('.count').css({color:'#000000',fontWeight:'normal'});
        }
    });
    $(window).load(function(){
        $('.count').html(countMax);
    });
});

  jQuery('.check input[type=checkbox]').click(function(){
    var checked = jQuery('input[type=checkbox]:checked').length;
    if (checked > 7) {
      jQuery(this).prop("checked",false);
      alert('それ以上は選択できません。');
    }
  });


  jQuery('.user_remove input[type=checkbox]').click(function(){
      jQuery(this).prop("checked");
      $('#avatar_prev').replaceWith('<%= image_tag 'default.png', id: :avatar_prev, :class => "img default" %>');
      $('.user_remove').hide();
  });

$(function() {
    if ($('#avatar_prev').get(0)) {
    }
 function readURL(input) {
   if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
       $('#avatar_prev').attr('src', e.target.result);
     }
     reader.readAsDataURL(input.files[0]);
      $('.user_remove').show();
      $('.user_remove input[type=checkbox]').prop('checked',false);
   }
 }
 $("#user_avatar").change(function(){
   readURL(this);
 });
});

</script>

app/views/users/followers.html.erb
<%= stylesheet_link_tag 'user/index', media: 'all', 'data-turbolinks-track': 'reload' %>

    <div class="user_index">
    <%= render partial: 'users/user', collection: @users %>
    </div>

app/views/users/followings.html.erb
<%= stylesheet_link_tag 'user/index', media: 'all', 'data-turbolinks-track': 'reload' %>



    <div class="user_index">
    <%= render partial: 'users/user', collection: @users %>
    </div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'user/index', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="user_index">
<%= render partial: 'users/user', collection: @users %>
</div>
<div class="paginate">
<%= paginate @users %>
</div>

app/views/users/search.html.erb
<%= stylesheet_link_tag 'user/index', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag    'products', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% if @users.length == 0 %>
     <div class="search_no">
        <% if user_signed_in? %>
        <p class="product_search">見つかりませんでした。<br ></p>
        <% else %>
        <p class="product_search">見つかりませんでした。<br >是非最初の登録者になりましょう。</p>
            <%= link_to(new_user_registration_path, :class=>"buttonA" ) do %>無料で会員登録<% end %><br >
            <p>または</p><br >
            <%= link_to(new_user_session_path, :class=>"buttonA buttonB" ) do %>ログイン<% end %>
        <% end %>
      </div>
    <% end %>
<div class="user_index">
<%= render partial: 'users/user', collection: @users %>
</div>
<div class="paginate">
<%= paginate @users %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag    'user/products', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'user/notices', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag    'swiper', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'swiper', 'data-turbolinks-track': 'reload' %>
<% provide :title, "#{@user.name} | " %>
<div class="user_page">
   <div class="container">
    <div class="userA">
      <div class="proA">
      <%= image_tag @user.avatar.url, :class => "image" %>
    <div class="proA-text">
      <h4><%= @user.name %><% if user_signed_in? && current_user.following?(@user)  %><%= fa_icon("check") %><% end %></h4>
          <% if @user.local? && @user.location? %>
        <a><%= fa_icon("map-marker") %></a><%= link_to @user.location, search_users_path(location: @user.location) %><a><%= @user.local%></a>
        <% elsif @user.location? %>
        <a><%= fa_icon("map-marker") %></a><a><%= @user.location %></a>
        <% elsif @user.local? %>
        <a><%= fa_icon("map-marker") %></a><a><%= @user.local %></a>
        <% end %>
        <% if user_signed_in? && @user.id == current_user.id %>
        <div class ="edituser post"><%= link_to fa_icon("edit")+"投稿", new_product_path %>
        <%= link_to fa_icon("cog")+"編集", edit_user_path(current_user) %></div>
        <% end %>
      </div>
      </div>
    <nav class="profile">
      <ul>
        <li class="btn3">
          <% if user_signed_in? %>
          <%= render partial: 'relationships/follow_button', user: @user %>
          <% end %>
          <% if @user.address? %>
        <%= link_to fa_icon("envelope")+'メール', user_emails_path(@user), class: "mail" %>
        <% end %>
          <% if @user.url? %>
        <%= link_to fa_icon("home")+'リンク', @user.url, class: "mail" %>
        <% end %>
      </li>
          <% if @user.office? %>
        <li><a><%= fa_icon("paperclip") %><%= @user.office %></a></li>
        <% end %>
        <% if @user.phone? %>
        <li><a><%= fa_icon("phone") %></a><a><%= @user.phone %></a></li>
        <% end %>
      </ul>
      <text><%= simple_format(@user.text) %></text>

    <div class="follow">
      <%= link_to(followings_user_path(@user), class: 'follow_btn') do %><p><%= @user.followings.count %> フォロー</p><% end %>
      <%= link_to(followers_user_path(@user), class: 'follow_btn') do %><p><%= @user.followers.count %> フォロワー</p><% end %>
      <%= link_to(search_products_path(user_id: @user.id), class: 'follow_btn') do %><p><%= @user.products.count %> ポスト</p><% end %>
    </div>
          <li><% @tags.each do | t | %>
          <p><%= link_to "##{t.work.tag}", search_users_path(work_id: t.work_id) %></p>
          <% end %></li>
    </nav>
    <div class="proB"><P><%= fa_icon("chevron-down") %>MoreProfile...</P></div>
   </div>

  <% if @notice %>
   <div class="userB">
    <div class="notice">
    <%= render partial: 'users/notice', locals: {notice: @notice} %>
       </div>
      </div>
    <% else %>
      <% if user_signed_in? && @user.id == current_user.id %>
      <div class="userB">
      <div class="notice">
        <h6>求人やイベントなどの情報を投稿したり共有することができます。</h6>
      <%= link_to link_to "お知らせを掲載する",  new_notice_path %>
    </div>
      </div>
      <% end %>
  <% end %>

   <div class="userB">
   <% if @user.products.exists? %>
     <p>最新のプロジェクト<button class="btn"><%= link_to "More", search_products_path(user_id: @user.id) %></button></p>

      <% if @products.count > 2 %>
       <div class=" swiper-container">
         <div class="swiper-wrapper">
         <%= render partial: 'users/product', collection: @products %>
         </div>
       </div>
       <% else %>
         <div class="swiper-wrapper">
         <%= render partial: 'users/product', collection: @products %>
         </div>
       <% end %>
    <% else %>
    <% if user_signed_in? && @user.id == current_user.id %>
    <div class="product_post">
    <h5>まだ投稿がありません。</h5>
    <h6>プロジェクトを投稿し公開することで、沢山の人達と共有したりコメントをもらうことが出来ます。</h6>
    <%= link_to fa_icon("edit")+"投稿する", new_product_path %>
    </div>
    <% else %>
    <div class="product_post">
    <h5>まだ投稿がありません。</h5>
     </div>
    <% end %>
   <% end %>
  </div>


   <% if @commented.count > 0 %>
   <div class="userB">
    <p>コメント済み<button class="btn"><%= link_to "More", search_comments_path(id: @user.id) %></button></p>

       <% if @commented.count > 2 %>
       <div class=" swiper-container">
       <div class="swiper-wrapper">
       <%= render partial: 'users/product', collection: @commented %>
       </div>
       </div>
       <% else %>
       <div class="swiper-wrapper">
       <%= render partial: 'users/product', collection: @commented %>
       </div>
     </div>
      <% end %>
   <% end %>
  </div>
</div>


 <script>

$(".proB").click(function(){
  $(".profile").slideToggle();
});

var mySwiper = new Swiper('.swiper-container', {
  infinite: true,
  loop: false,
  spaceBetween: 5,

  breakpoints: {
    // 767px以下になったら
    767: {
      slidesPerView: 2,
    },

    300: {
      slidesPerView: 1,
    }
  },
});
</script>