config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'top/about', to: 'top#about'
  get 'top/search', to: 'top#search'

  get 'relationships/create'
  get 'relationships/destroy'
  resources :relationships, only: [:create, :destroy]

  get 'inquiries', to: 'inquiries#index'
  post 'inquiries/confirm', to: 'inquiries#confirm'
  post 'inquiries/complete', to: 'inquiries#complete'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
  get 'emails', to: 'emails#index'
  post 'emails/confirm', to: 'emails#confirm'
  post 'emails/complete', to: 'emails#complete'
    member do
      get :followings
      get :followers
    end
    collection do
      get :search
      get :about
    end
  end

  resources :products do
     collection do
      get :search
      get :about
    end
  end

  resources :comments, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :search
    end
  end

resources :notices do
      collection do
      get :search
      get :about
    end
  end

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => '問い合わせ内容を入力してください'}
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def complete
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.inquiry_email(@inquiry).deliver_now
    # 完了画面を表示
    render :action => 'complete'
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/complete.html.erb
<%= stylesheet_link_tag    'product/show', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="product_page">
<div class="createpage">
<p>
  お問い合わせが完了しました。
</p>
<%= link_to "ホームに戻る", root_path %>
</div>
</div>

app/views/inquiries/confirm.html.erb
<%= stylesheet_link_tag    'devise/user', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= form_with model: @inquiry, :url => inquiries_complete_path, local: true do |f| %>
  <div class="usernew">
    <h3>お問い合わせ内容確認</h3>

  <div class="field">
  <p><%= f.label :"名前" %></p>
  <%= f.hidden_field :name %>
  <div class=" form"><%= @inquiry.name %></div>
  </div>

  <div class="field">
  <p><%= f.label :"メールアドレス" %></p>
  <%= f.hidden_field :email %>
  <div class=" form"><%= @inquiry.email %></div>
  </div>

  <div class="field">
  <p><%= f.label :"お問い合わせ内容" %></p>
  <%= f.hidden_field :message %>
  <div class="form"><%= simple_format(@inquiry.message) %></div>
  </div>


  <%= f.submit '確認',class: 'user button' %>
  </div>
  <% end %>
  </div>

app/views/inquiries/index.html.erb
<%= stylesheet_link_tag    'devise/user', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= form_with model: @inquiry, :url => inquiries_confirm_path, local: true do |f| %>
  <div class="usernew">
    <h3>お問い合わせ</h3>
    <p>（ ※は必須です。 ）</p>

  <% if @inquiry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @inquiry.errors.each do |attr, msg| %>
          <p><%= msg %></p>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
  <p><%= f.label :"名前" %><a>※</a></p>
  <%= f.text_field :name, class: 'user form' %>
  </div>

  <div class="field">
  <p><%= f.label :"メールアドレス" %><a>※</a></p>
  <%= f.email_field :email, class: 'user form' %>
  </div>

  <div class="field">
  <p><%= f.label :"お問い合わせ内容" %><a>※</a></p>
  <%= f.text_area :message, class: 'user form text' %>
  </div>

  <div class="field">
  <%= f.submit '確認',class: 'user button' %>
  </div>
  <% end %>
  </div>