config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'top/about', to: 'top#about'
  get 'top/search', to: 'top#search'

  get 'relationships/create'
  get 'relationships/destroy'
  resources :relationships, only: [:create, :destroy]

  get 'inquiries', to: 'inquiries#index'
  post 'inquiries/confirm', to: 'inquiries#confirm'
  post 'inquiries/complete', to: 'inquiries#complete'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
  get 'emails', to: 'emails#index'
  post 'emails/confirm', to: 'emails#confirm'
  post 'emails/complete', to: 'emails#complete'
    member do
      get :followings
      get :followers
    end
    collection do
      get :search
      get :about
    end
  end

  resources :products do
     collection do
      get :search
      get :about
    end
  end

  resources :comments, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :search
    end
  end

resources :notices do
      collection do
      get :search
      get :about
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord

  is_impressionable counter_cache: true

  default_scope { order(created_at: :desc)}

  # scope :has_genre_id_all, -> genre_ids {
  #   product = arel_table
  #   genre_product = GenreProduct.arel_table
  #   subquery = genre_product.project(genre_product[:product_id])
  #   .where(genre_product[:genre_id].in(genre_ids))
  #   .group(genre_product[:product_id])
  #   .having(genre_product[:genre_id].count('distinct').eq(genre_ids.size))
  #   where(product[:id].in(subquery))
  # }

  belongs_to :user
  counter_culture :user

  has_many :interiors, inverse_of: :product, dependent: :delete_all
  accepts_nested_attributes_for :interiors, reject_if: :all_blank, allow_destroy: true

  has_many :whole_photos, inverse_of: :product, dependent: :delete_all
  accepts_nested_attributes_for :whole_photos, reject_if: :all_blank, allow_destroy: true

  has_many :details, inverse_of: :product, dependent: :delete_all
  accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true

  has_many :genre_products, dependent: :delete_all
  has_many :genres, through: :genre_products, dependent: :delete_all
  accepts_nested_attributes_for :genre_products, allow_destroy: true

  has_many :comments, ->{ order("updated_at DESC")}, dependent: :delete_all

  validate :add_error

  def self.search_genre(genres)
      productgenre = GenreProduct.searchgenres(genres)
      self.where(id: productgenre)
  end

  def self.count_order(count)
    if count == "1"
      self.reorder('comments_count DESC')
    elsif count == "2"
    self.reorder('impressions_count DESC')
    elsif count == "3"
      self.reorder('created_at DESC')
    elsif count == "4"
    self.reorder('created_at ASC')
    end
  end



  def add_error
    errors[:base] << "タイトル" if title.blank?
    errors[:base] << "写真" if whole_photos.length == 0
    errors[:base] << "工期" if whet.blank?
    errors[:base] << "場所" if location.blank?
    errors[:base] << "床面積" if area.blank?
    errors[:base] << "コンセプト" if text.blank?
    errors[:base] << "カテゴリー" if category.blank?
  end

  validates :text, length: { maximum: 350 }
  validates :title, length: { maximum: 15 }
  validates :subtitle, length: { maximum: 30 }


  enum category: {
    "ホテル・旅館":1, "物販店・専門店":2, "オフィス・スクール":3, "バー・クラブ":4, "カフェ・レストラン":5, 居酒屋:6, "各国料理・ダイニングレストラン":7, "和洋菓子・フードストア":8, "ブティック・アパレル雑貨":9, "クリニック・ビューティー":10, "戸建て新築・リノベーション":11, マンションリノベーション:12, "イベント・大型商業施設":13, その他:14
  }

  enum charge: {
    "設計・デザイン":1, アシスタント:2
  }

  enum location: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,海外:48
  }



 # def self.search(search_location,search_category)

 #    where(['content LIKE ?', "%#{search}%"]).where(['content LIKE ?', "%#{search}%"])

 #  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  impressionist :actions=> [:show]

 def index
  @photos = WholePhoto.group(:product_id)
  @products = Product.select(:id, :title, :location, :category, :completion).page(params[:page]).per(20)
 end

   def show
    @product = Product.find(params[:id])
    @photos = @product.whole_photos
    @tags = @product.genre_products
    comments = Comment.all
    @comments = @product.comments
    @comment = Comment.new
    @comment.product_id = @product.id
  end


  def search
   @products = Product.select(:id, :title, :location, :category, :completion)
   @photos = WholePhoto.group(:product_id)
   @products = @products.count_order(params[:count]) if params[:count].present?
   @products = @products.where(location: params[:location]) if params[:location].present?
   @products = @products.where(category: params[:category]) if params[:category].present?
   # productgenre = GenreProduct.where(genre_id: params[:genre_id]).select(:product_id) if params[:genre_id].present?
   # @products = @products.where(id: productgenre)
   @products = @products.search_genre(params[:genres]) if params[:genres] && params[:genres].compact.reject(&:empty?).present?
   @products = @products.search_genre(params[:genre_id]) if params[:genre_id].present?
   @products = @products.where(user_id: params[:user_id]) if params[:user_id].present?
   @products = @products.page(params[:page]).per(20)
  end

  def about
  end

  def new
    @product = Product.new
    @user = User.find(current_user.id)
    @photos = 8.times { @product.whole_photos.build }
    @product.user = @user
    5.times { @product.interiors.build }
  end

  def create
     @product = Product.new(create_params)
    if @product.save
    else
      @photos = ( 8 - @product.whole_photos.to_a.count ).times { @product.whole_photos.build }
      ( 5 - @product.interiors.to_a.count ).times { @product.interiors.build }
      render action: :new
    end
  end

def destroy
  product = Product.find(params[:id])
  product.destroy if product.user_id == current_user.id
  redirect_to user_path(current_user)
end

  def edit
  @product = Product.find(params[:id])
  @user = current_user
  @photos = @product.whole_photos.select(:id, :photo)
  @interior = @product.interiors
  ( 8 - @photos.length).times { @product.whole_photos.build }
  ( 5 - @interior.length).times { @product.interiors.build }
  end

  def update
    @product = Product.find(params[:id])
   if user_signed_in? && current_user == @product.user
     if @product.update(update_params)
     redirect_to user_path(current_user)
     else
     @photos = ( 8 - @product.whole_photos.to_a.count ).times { @product.whole_photos.build }
     @interior = ( 5 - @product.interiors.to_a.count ).times { @product.interiors.build }
     render action: :edit
     end
   end
  end

  private

  def create_params
    params.require(:product).permit(:title, :subtitle, :charge, :whet, :completion, :location, :area, :text, :category, { :genre_ids=> [] }, whole_photos_attributes:[:id, :photo, :photo_cache,:title, :text, :_destroy], interiors_attributes:[:id, :room_name, :material_one, :material_two, :material_three, :material_four, :material_five, :material_six]).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:product).permit(:title, :subtitle, :charge, :whet, :completion, :location, :area, :text, :category, { :genre_ids=> [] }, whole_photos_attributes:[:id, :photo, :photo_cache,:title, :text, :_destroy ], interiors_attributes:[:id, :room_name, :material_one, :material_two, :material_three, :material_four, :material_five, :material_six] ).merge(user_id: current_user.id)
  end




  # def create_detail_params

  # end

  # def create_whole_photo_params

  # end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_detail.html.erb
<article>
<%= image_tag detail.image_url, :class => "photos" %>
<div class="text">
<h5><%= detail.title %></h5>
<p><%= simple_format(detail.text) %></p>
</div>
</article>

app/views/products/_photo.html.erb
<%= image_tag photo.photo_url %>

app/views/products/_product.html.erb
<article>
     <% @photos.each do | top | %>
        <% if product.id == top.product_id %>
        <%= link_to image_tag(top.photo_url), product_path(product.id), :class => "img" %>
        <% end %>
     <% end %>
    <div class="text">
        <div class="title"><h6><%= product.title %></h6></div>
        <p><%= fa_icon("map-marker") %><%= product.location %></p>
        <p><%= link_to product.category, search_products_path(category: product.category) %></p>
        <p><%= product.completion.strftime("%Y-%m") %>  <%= fa_icon("comments") %><%= product.comments.count %><%= fa_icon("eye") %><%= product.impressions.count %></p>
     </div>
</article>

app/views/products/about.html.erb
<%= stylesheet_link_tag    'product/new', media: 'all', 'data-turbolinks-track': 'reload' %>
<% provide :title, "ABOUT | " %>
<div class="product_new">
　<div class="container">

  <h3>建築事例を検索</h3>

<%= form_with url: search_products_path, method: :get, local: true do |f| %>

  <div class="field">
  <p><%= f.label :場所 %></p>
  <%= f.select :location, Product.locations.keys, {prompt: '選択してください'}, class: 'product form' %><br />
  </div>

  <div class="field">
  <p><%= f.label :カテゴリー %></p>
  <%= f.select :category, Product.categories.keys, {prompt: '選択してください'}, class: 'product form' %><br />
  </div>

  <div class="field">
  <p><%= f.label :関連キーワード %></p>
    <label><div class= "tag"><%= f.collection_check_boxes(:genres, Genre.all, :id, :tag) do |b| %>
      <%=  b.check_box %><a><%= b.label { b.text } %></a>
      <% end %></div>
     </label>
     </div>

  <div class="field">
  <p><%= f.label :表示の順番 %></p>
  <%= f.select :count, [["コメントが多い順", "1"], ["アクセス数が多い順", "2"], ["投稿が新しい順", "3"], ["投稿が古い順", "4"]], {prompt: '選択してください'}, class: 'product form' %><br />
  </div>



  <div class="field">
  <%= f.submit "検索", class: 'product button', name: nil %>
  </div>

    <% end %>
　</div>
</div>

app/views/products/create.html.erb
<%= stylesheet_link_tag    'product/show', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="product_page">
  <div class="createpage">
  <p>投稿が完了しました。</p>
  <div class="btn">
  <%= link_to "ページを確認する", product_path(@product) %>
  </div>
  <div class="btn">
  <%= link_to "マイページへ移動する", user_path(current_user) %>
</div>
</div>
</div>

app/views/products/index.html.erb
<%= stylesheet_link_tag    'products', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="index-container">
<%= render partial: 'products/product', collection: @products %>
</div>
<div class="paginate">
<%= paginate @products %>
</div>

app/views/products/new.html.erb
<%= stylesheet_link_tag    'product/new', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag    'swiper', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'swiper', 'data-turbolinks-track': 'reload' %>
<% provide :title, "新規作成 | " %>

<div class="product_new" id="product_new">

<div class="container">

<h3>建築事例を投稿</h3>
<h4>（ ※は必須 ）</h4>
<%= render 'form', product:@product %>
　</div>
</div>

app/views/products/search.html.erb
<%= stylesheet_link_tag    'products', media: 'all', 'data-turbolinks-track': 'reload' %>

    <% if @products.length == 0 %>
     <div class="search_no">
        <% if user_signed_in? %>
        <p class="product_search">まだ投稿されていません。<br >是非１番に投稿しましょう。</p>
            <%= link_to(new_product_path, :class=>"buttonA" ) do %>投稿する<% end %>
        <% else %>
        <p class="product_search">まだ投稿されていません。<br >是非１番に投稿しましょう。</p>
            <%= link_to(new_user_registration_path, :class=>"buttonA" ) do %>無料で会員登録<% end %><br >
            <p>または</p><br >
            <%= link_to(new_user_session_path, :class=>"buttonA buttonB" ) do %>ログイン<% end %>
        <% end %>
      </div>
    <% end %>

<div class="index-container">
<%= render partial: 'products/product', collection: @products %>
</div>
<div class="paginate">
<%= paginate @products %>
</div>

app/views/products/show.html.erb
<%= stylesheet_link_tag    'product/show', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag    'product/comment', media: 'all', 'data-turbolinks-track': 'reload' %>
<% provide :title, "#{@product.title} | " %>
<div class="product_page">
  <div class="container">
   <div class="product_conA">
    <div class="proA">
        <% @photos.each do | img | %>
          <%= image_tag img.photo_url, :class => "photos" %>
          <div class="text">
          <h5><%= img.title %></h5>
          <p><%= img.text %></p>
          </div>
        <% end %>
    </div>
  <div class="product_conB">
     <div class="proB">
         <nav class="profile">
            <li><h4><%= @product.title %></h4></li>
            <li><%= @product.subtitle %></li>
            <li><%= link_to @product.category, search_products_path(category: @product.category) %></li>
            <li>完成：<%= @product.completion.strftime("%Y年%m月") %></li>
            <li><a>場所：<%= link_to @product.location, search_products_path(location: @product.location) %></a></li>
            <li>面積：<%= @product.area %>㎡</li>
            <li>工期：<%= @product.whet %>ヶ月</li>
            <li><a>投稿者：</a><%= link_to @product.user.name, user_path(@product.user.id) %></li>
            <li><text><%= simple_format(@product.text) %></text></li>
         </nav>
     </div>
  <div class="proE">
    <h5>仕上げ</h5>
    <% @product.interiors.each do |i| %>
    <% if i.room_name? %><p><%= i.room_name %>：</p><% end %>
    <table>
    <% if i.material_one? %><tr><td>天井</td><td><%= i.material_one %></td></tr><% end %>
    <% if i.material_two? %><tr><td>壁</td><td><%= i.material_two %></td></tr><% end %>
    <% if i.material_three? %><tr><td>床</td><td><%= i.material_three %></td></tr><% end %>
    <% if i.material_four? %><tr><td>設備・照明</td><td><%= i.material_four %></td></tr><% end %>
    <% if i.material_five? %><tr><td>家具・建具</td><td><%= i.material_five %></td></tr><% end %>
    <% if i.material_six? %><tr><td>その他</td><td><%= i.material_six %></td></tr><% end %>
    </table>
    <% end %>
  </div>
   <div class="proC">
     <nav class="profile">
     <ul>
      <li>関連キーワード</li>
      <li><% @tags.each do | t | %>
      <div class="tagA"><p><%= link_to "##{t.genre.tag}", search_products_path(genre_id: t.genre_id), :class => "tags" %></p></div>
      <% end %></li>
       </ul>
     </nav>
   </div>
  </div>
  </div>

<div class="shere-btn">
  <div class="facebook btn">
  <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.archinect-japan.com/products/<%= @product.id %>" title="<%= @product.title %>"><%= fa_icon("facebook-square") %>シェア</a></div>

  <div class="twitter btn">
  <a href="http://twitter.com/share?url=https://www.archinect-japan.com/products/<%= @product.id %>" title="<%= @product.title %>"><%= fa_icon("twitter") %>ツイート</a></div>

  <div class="line btn">
  <a href="http://line.me/R/msg/text/?https://www.archinect-japan.com/products/<%= @product.id %>"><%= fa_icon("comment") %>LINEで送る</a></div>
</div>

     <% if user_signed_in? && @product.user_id == current_user.id %>
       <div class="edituser" ><%= link_to "編集", edit_product_path(id: @product.id ) %><%= link_to '削除', "/products/#{@product.id}", method: :delete, data:{confirm: '削除しますか？'} %></div>
     <% end %>


  <div class="proD">
  <% if user_signed_in? %>
   <%= form_with model:  @comment, local: true  do |f| %>

    <div class="field">
    <%= f.text_area :text, autocomplete: "text",  placeholder: "コメント（１００文字以内）" , :maxlength => "100", class: ' form' %>
    </div>

    <div class="field">
    <%= f.hidden_field :product_id %>
    <%= f.submit "コメントを投稿", class: 'post btn' %>
    </div>
    <% end %>
  <% else %>
  <p>コメントを投稿するには<%= link_to "ログイン", new_user_session_path %>して下さい。</p>
  <% end %>

　　<div class="count"><p>コメント数：（<%= @comments.count %>）</p></div>
   <%= render partial: 'comments/comment', collection: @comments %>
   </div>

     </div>
</div>